name: Deploy to Koyeb

on:
  push:
    branches:
      - main  # Change this to your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y curl

    - name: Log in to Koyeb CLI
      run: |
        # Check if Koyeb CLI is already installed
        if ! command -v koyeb &> /dev/null
        then
            echo "Koyeb CLI not found, installing..."
            curl -sSL https://cli.koyeb.com | sudo bash
        fi
        koyeb --version  # Verify Koyeb CLI installation
        koyeb login --token ${{ secrets.KOYEB_API_TOKEN }}  # Use Koyeb API Token from Secrets

    - name: Deploy to Koyeb
      run: |
        koyeb app update --image ghcr.io/redgale/dockefileforai:latest --name ai-website  # App name updated to 'ai-website'
