name: Deploy to Koyeb

on:
  workflow_dispatch:  # Allows you to manually trigger the workflow from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io  # Using GitHub Container Registry

    - name: Pull Docker image from GitHub Container Registry
      run: |
        docker pull ghcr.io/redgale/dockefileforai:latest  # Replace with your actual image name

    - name: Install Koyeb CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh | sh
        koyeb --version  # Verify Koyeb CLI installation

    - name: Log in to Koyeb CLI
      run: |
        koyeb login --token ${{ secrets.KOYEB_API_TOKEN }}  # Use your Koyeb API Token stored in GitHub Secrets

    - name: Deploy to Koyeb
      run: |
        koyeb app update --image ghcr.io/redgale/dockefileforai:latest --name ai-website  # Replace with your app name
