name: Deploy to Koyeb

on:
  push:
    branches:
      - main  # Change this to your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl

    - name: Cache Koyeb CLI
      id: koyeb_cache
      uses: actions/cache@v3
      with:
        path: ~/.koyeb
        key: ${{ runner.os }}-koyeb-${{ hashFiles('**/koyeb-cli.sh') }}
        restore-keys: |
          ${{ runner.os }}-koyeb-

    - name: Install or Update Koyeb CLI
      run: |
        if ! command -v koyeb &> /dev/null; then
          echo "Koyeb CLI not found, installing..."
          curl -fsSL https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh | sh
        else
          echo "Koyeb CLI found, updating..."
          sudo koyeb update
        fi
        echo 'export PATH="$HOME/.koyeb/bin:$PATH"' >> $GITHUB_ENV
        source $GITHUB_ENV

    - name: Log in to Koyeb CLI
      run: koyeb login --token ${{ secrets.KOYEB_API_TOKEN }}

    - name: Deploy to Koyeb
      run: koyeb app update --image ghcr.io/redgale/dockefileforai:latest --name ai-website  # App name updated to 'ai-website'
